# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: getConfigService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import testData_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='getConfigService.proto',
  package='protobuftest',
  serialized_pb=_b('\n\x16getConfigService.proto\x12\x0cprotobuftest\x1a\x0etestData.proto2W\n\x10GetConfigService\x12\x43\n\tgetConfig\x12\x1b.protobuftest.ConfigRequest\x1a\x19.protobuftest.ConfigReplyB\x1f\n\x07rpcdataB\x0eMyProtoService\x88\x01\x01\x90\x01\x01')
  ,
  dependencies=[testData_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)





DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\007rpcdataB\016MyProtoService\210\001\001\220\001\001'))

_GETCONFIGSERVICE = _descriptor.ServiceDescriptor(
  name='GetConfigService',
  full_name='protobuftest.GetConfigService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=56,
  serialized_end=143,
  methods=[
  _descriptor.MethodDescriptor(
    name='getConfig',
    full_name='protobuftest.GetConfigService.getConfig',
    index=0,
    containing_service=None,
    input_type=testData_pb2._CONFIGREQUEST,
    output_type=testData_pb2._CONFIGREPLY,
    options=None,
  ),
])

GetConfigService = service_reflection.GeneratedServiceType('GetConfigService', (_service.Service,), dict(
  DESCRIPTOR = _GETCONFIGSERVICE,
  __module__ = 'getConfigService_pb2'
  ))

GetConfigService_Stub = service_reflection.GeneratedServiceStubType('GetConfigService_Stub', (GetConfigService,), dict(
  DESCRIPTOR = _GETCONFIGSERVICE,
  __module__ = 'getConfigService_pb2'
  ))


# @@protoc_insertion_point(module_scope)
