# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: testData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='testData.proto',
  package='protobuftest',
  serialized_pb=_b('\n\x0etestData.proto\x12\x0cprotobuftest\"\xd7\x01\n\x0b\x43onfigReply\x12\x16\n\x0ehttp_server_ip\x18\x01 \x01(\t\x12\r\n\x05tc_ip\x18\x02 \x01(\t\x12\r\n\x05tc_if\x18\x03 \x01(\t\x12\x17\n\x0f\x62inary_share_ip\x18\x04 \x01(\t\x12\x43\n\x0bplayer_type\x18\x05 \x01(\x0e\x32$.protobuftest.ConfigReply.PlayerType:\x08\x42\x43M97208\"4\n\nPlayerType\x12\x0c\n\x08\x42\x43M97208\x10\x00\x12\x0b\n\x07LINUX32\x10\x01\x12\x0b\n\x07\x41NDROID\x10\x02\" \n\rConfigRequest\x12\x0f\n\x07version\x18\x01 \x01(\tB\x17\n\x07rpcdataB\x0c\x43onfigProtos')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CONFIGREPLY_PLAYERTYPE = _descriptor.EnumDescriptor(
  name='PlayerType',
  full_name='protobuftest.ConfigReply.PlayerType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BCM97208', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LINUX32', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANDROID', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=196,
  serialized_end=248,
)
_sym_db.RegisterEnumDescriptor(_CONFIGREPLY_PLAYERTYPE)


_CONFIGREPLY = _descriptor.Descriptor(
  name='ConfigReply',
  full_name='protobuftest.ConfigReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='http_server_ip', full_name='protobuftest.ConfigReply.http_server_ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tc_ip', full_name='protobuftest.ConfigReply.tc_ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tc_if', full_name='protobuftest.ConfigReply.tc_if', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='binary_share_ip', full_name='protobuftest.ConfigReply.binary_share_ip', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player_type', full_name='protobuftest.ConfigReply.player_type', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONFIGREPLY_PLAYERTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=248,
)


_CONFIGREQUEST = _descriptor.Descriptor(
  name='ConfigRequest',
  full_name='protobuftest.ConfigRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='protobuftest.ConfigRequest.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=250,
  serialized_end=282,
)

_CONFIGREPLY.fields_by_name['player_type'].enum_type = _CONFIGREPLY_PLAYERTYPE
_CONFIGREPLY_PLAYERTYPE.containing_type = _CONFIGREPLY
DESCRIPTOR.message_types_by_name['ConfigReply'] = _CONFIGREPLY
DESCRIPTOR.message_types_by_name['ConfigRequest'] = _CONFIGREQUEST

ConfigReply = _reflection.GeneratedProtocolMessageType('ConfigReply', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGREPLY,
  __module__ = 'testData_pb2'
  # @@protoc_insertion_point(class_scope:protobuftest.ConfigReply)
  ))
_sym_db.RegisterMessage(ConfigReply)

ConfigRequest = _reflection.GeneratedProtocolMessageType('ConfigRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGREQUEST,
  __module__ = 'testData_pb2'
  # @@protoc_insertion_point(class_scope:protobuftest.ConfigRequest)
  ))
_sym_db.RegisterMessage(ConfigRequest)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\007rpcdataB\014ConfigProtos'))
# @@protoc_insertion_point(module_scope)
