// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: testData.proto

package rpcdata;

public final class ConfigProtos {
  private ConfigProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ConfigReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuftest.ConfigReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string http_server_ip = 1;</code>
     *
     * <pre>
     *server to connect to
     * </pre>
     */
    boolean hasHttpServerIp();
    /**
     * <code>optional string http_server_ip = 1;</code>
     *
     * <pre>
     *server to connect to
     * </pre>
     */
    java.lang.String getHttpServerIp();
    /**
     * <code>optional string http_server_ip = 1;</code>
     *
     * <pre>
     *server to connect to
     * </pre>
     */
    com.google.protobuf.ByteString
        getHttpServerIpBytes();

    /**
     * <code>optional string tc_ip = 2;</code>
     *
     * <pre>
     *traffic controller ip address
     * </pre>
     */
    boolean hasTcIp();
    /**
     * <code>optional string tc_ip = 2;</code>
     *
     * <pre>
     *traffic controller ip address
     * </pre>
     */
    java.lang.String getTcIp();
    /**
     * <code>optional string tc_ip = 2;</code>
     *
     * <pre>
     *traffic controller ip address
     * </pre>
     */
    com.google.protobuf.ByteString
        getTcIpBytes();

    /**
     * <code>optional string tc_if = 3;</code>
     *
     * <pre>
     *interface name to configure traffic controller on
     * </pre>
     */
    boolean hasTcIf();
    /**
     * <code>optional string tc_if = 3;</code>
     *
     * <pre>
     *interface name to configure traffic controller on
     * </pre>
     */
    java.lang.String getTcIf();
    /**
     * <code>optional string tc_if = 3;</code>
     *
     * <pre>
     *interface name to configure traffic controller on
     * </pre>
     */
    com.google.protobuf.ByteString
        getTcIfBytes();

    /**
     * <code>optional string binary_share_ip = 4;</code>
     */
    boolean hasBinaryShareIp();
    /**
     * <code>optional string binary_share_ip = 4;</code>
     */
    java.lang.String getBinaryShareIp();
    /**
     * <code>optional string binary_share_ip = 4;</code>
     */
    com.google.protobuf.ByteString
        getBinaryShareIpBytes();

    /**
     * <code>optional .protobuftest.ConfigReply.PlayerType player_type = 5 [default = BCM97208];</code>
     */
    boolean hasPlayerType();
    /**
     * <code>optional .protobuftest.ConfigReply.PlayerType player_type = 5 [default = BCM97208];</code>
     */
    rpcdata.ConfigProtos.ConfigReply.PlayerType getPlayerType();
  }
  /**
   * Protobuf type {@code protobuftest.ConfigReply}
   *
   * <pre>
   *configuration data to configure a video player 
   * </pre>
   */
  public static final class ConfigReply extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuftest.ConfigReply)
      ConfigReplyOrBuilder {
    // Use ConfigReply.newBuilder() to construct.
    private ConfigReply(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ConfigReply(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ConfigReply defaultInstance;
    public static ConfigReply getDefaultInstance() {
      return defaultInstance;
    }

    public ConfigReply getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ConfigReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              httpServerIp_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              tcIp_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              tcIf_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              binaryShareIp_ = bs;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              rpcdata.ConfigProtos.ConfigReply.PlayerType value = rpcdata.ConfigProtos.ConfigReply.PlayerType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                playerType_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rpcdata.ConfigProtos.internal_static_protobuftest_ConfigReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rpcdata.ConfigProtos.internal_static_protobuftest_ConfigReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rpcdata.ConfigProtos.ConfigReply.class, rpcdata.ConfigProtos.ConfigReply.Builder.class);
    }

    public static com.google.protobuf.Parser<ConfigReply> PARSER =
        new com.google.protobuf.AbstractParser<ConfigReply>() {
      public ConfigReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConfigReply(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ConfigReply> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code protobuftest.ConfigReply.PlayerType}
     */
    public enum PlayerType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>BCM97208 = 0;</code>
       */
      BCM97208(0, 0),
      /**
       * <code>LINUX32 = 1;</code>
       */
      LINUX32(1, 1),
      /**
       * <code>ANDROID = 2;</code>
       */
      ANDROID(2, 2),
      ;

      /**
       * <code>BCM97208 = 0;</code>
       */
      public static final int BCM97208_VALUE = 0;
      /**
       * <code>LINUX32 = 1;</code>
       */
      public static final int LINUX32_VALUE = 1;
      /**
       * <code>ANDROID = 2;</code>
       */
      public static final int ANDROID_VALUE = 2;


      public final int getNumber() { return value; }

      public static PlayerType valueOf(int value) {
        switch (value) {
          case 0: return BCM97208;
          case 1: return LINUX32;
          case 2: return ANDROID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PlayerType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<PlayerType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PlayerType>() {
              public PlayerType findValueByNumber(int number) {
                return PlayerType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return rpcdata.ConfigProtos.ConfigReply.getDescriptor().getEnumTypes().get(0);
      }

      private static final PlayerType[] VALUES = values();

      public static PlayerType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private PlayerType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protobuftest.ConfigReply.PlayerType)
    }

    private int bitField0_;
    public static final int HTTP_SERVER_IP_FIELD_NUMBER = 1;
    private java.lang.Object httpServerIp_;
    /**
     * <code>optional string http_server_ip = 1;</code>
     *
     * <pre>
     *server to connect to
     * </pre>
     */
    public boolean hasHttpServerIp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string http_server_ip = 1;</code>
     *
     * <pre>
     *server to connect to
     * </pre>
     */
    public java.lang.String getHttpServerIp() {
      java.lang.Object ref = httpServerIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          httpServerIp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string http_server_ip = 1;</code>
     *
     * <pre>
     *server to connect to
     * </pre>
     */
    public com.google.protobuf.ByteString
        getHttpServerIpBytes() {
      java.lang.Object ref = httpServerIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        httpServerIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TC_IP_FIELD_NUMBER = 2;
    private java.lang.Object tcIp_;
    /**
     * <code>optional string tc_ip = 2;</code>
     *
     * <pre>
     *traffic controller ip address
     * </pre>
     */
    public boolean hasTcIp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string tc_ip = 2;</code>
     *
     * <pre>
     *traffic controller ip address
     * </pre>
     */
    public java.lang.String getTcIp() {
      java.lang.Object ref = tcIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tcIp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string tc_ip = 2;</code>
     *
     * <pre>
     *traffic controller ip address
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTcIpBytes() {
      java.lang.Object ref = tcIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tcIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TC_IF_FIELD_NUMBER = 3;
    private java.lang.Object tcIf_;
    /**
     * <code>optional string tc_if = 3;</code>
     *
     * <pre>
     *interface name to configure traffic controller on
     * </pre>
     */
    public boolean hasTcIf() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string tc_if = 3;</code>
     *
     * <pre>
     *interface name to configure traffic controller on
     * </pre>
     */
    public java.lang.String getTcIf() {
      java.lang.Object ref = tcIf_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tcIf_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string tc_if = 3;</code>
     *
     * <pre>
     *interface name to configure traffic controller on
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTcIfBytes() {
      java.lang.Object ref = tcIf_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tcIf_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BINARY_SHARE_IP_FIELD_NUMBER = 4;
    private java.lang.Object binaryShareIp_;
    /**
     * <code>optional string binary_share_ip = 4;</code>
     */
    public boolean hasBinaryShareIp() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string binary_share_ip = 4;</code>
     */
    public java.lang.String getBinaryShareIp() {
      java.lang.Object ref = binaryShareIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          binaryShareIp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string binary_share_ip = 4;</code>
     */
    public com.google.protobuf.ByteString
        getBinaryShareIpBytes() {
      java.lang.Object ref = binaryShareIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        binaryShareIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLAYER_TYPE_FIELD_NUMBER = 5;
    private rpcdata.ConfigProtos.ConfigReply.PlayerType playerType_;
    /**
     * <code>optional .protobuftest.ConfigReply.PlayerType player_type = 5 [default = BCM97208];</code>
     */
    public boolean hasPlayerType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .protobuftest.ConfigReply.PlayerType player_type = 5 [default = BCM97208];</code>
     */
    public rpcdata.ConfigProtos.ConfigReply.PlayerType getPlayerType() {
      return playerType_;
    }

    private void initFields() {
      httpServerIp_ = "";
      tcIp_ = "";
      tcIf_ = "";
      binaryShareIp_ = "";
      playerType_ = rpcdata.ConfigProtos.ConfigReply.PlayerType.BCM97208;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getHttpServerIpBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTcIpBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTcIfBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getBinaryShareIpBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, playerType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getHttpServerIpBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTcIpBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTcIfBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getBinaryShareIpBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, playerType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static rpcdata.ConfigProtos.ConfigReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rpcdata.ConfigProtos.ConfigReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rpcdata.ConfigProtos.ConfigReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rpcdata.ConfigProtos.ConfigReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rpcdata.ConfigProtos.ConfigReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static rpcdata.ConfigProtos.ConfigReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static rpcdata.ConfigProtos.ConfigReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static rpcdata.ConfigProtos.ConfigReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static rpcdata.ConfigProtos.ConfigReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static rpcdata.ConfigProtos.ConfigReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rpcdata.ConfigProtos.ConfigReply prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuftest.ConfigReply}
     *
     * <pre>
     *configuration data to configure a video player 
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuftest.ConfigReply)
        rpcdata.ConfigProtos.ConfigReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rpcdata.ConfigProtos.internal_static_protobuftest_ConfigReply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rpcdata.ConfigProtos.internal_static_protobuftest_ConfigReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                rpcdata.ConfigProtos.ConfigReply.class, rpcdata.ConfigProtos.ConfigReply.Builder.class);
      }

      // Construct using rpcdata.ConfigProtos.ConfigReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        httpServerIp_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        tcIp_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        tcIf_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        binaryShareIp_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        playerType_ = rpcdata.ConfigProtos.ConfigReply.PlayerType.BCM97208;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rpcdata.ConfigProtos.internal_static_protobuftest_ConfigReply_descriptor;
      }

      public rpcdata.ConfigProtos.ConfigReply getDefaultInstanceForType() {
        return rpcdata.ConfigProtos.ConfigReply.getDefaultInstance();
      }

      public rpcdata.ConfigProtos.ConfigReply build() {
        rpcdata.ConfigProtos.ConfigReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public rpcdata.ConfigProtos.ConfigReply buildPartial() {
        rpcdata.ConfigProtos.ConfigReply result = new rpcdata.ConfigProtos.ConfigReply(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.httpServerIp_ = httpServerIp_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.tcIp_ = tcIp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.tcIf_ = tcIf_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.binaryShareIp_ = binaryShareIp_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.playerType_ = playerType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rpcdata.ConfigProtos.ConfigReply) {
          return mergeFrom((rpcdata.ConfigProtos.ConfigReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(rpcdata.ConfigProtos.ConfigReply other) {
        if (other == rpcdata.ConfigProtos.ConfigReply.getDefaultInstance()) return this;
        if (other.hasHttpServerIp()) {
          bitField0_ |= 0x00000001;
          httpServerIp_ = other.httpServerIp_;
          onChanged();
        }
        if (other.hasTcIp()) {
          bitField0_ |= 0x00000002;
          tcIp_ = other.tcIp_;
          onChanged();
        }
        if (other.hasTcIf()) {
          bitField0_ |= 0x00000004;
          tcIf_ = other.tcIf_;
          onChanged();
        }
        if (other.hasBinaryShareIp()) {
          bitField0_ |= 0x00000008;
          binaryShareIp_ = other.binaryShareIp_;
          onChanged();
        }
        if (other.hasPlayerType()) {
          setPlayerType(other.getPlayerType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        rpcdata.ConfigProtos.ConfigReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (rpcdata.ConfigProtos.ConfigReply) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object httpServerIp_ = "";
      /**
       * <code>optional string http_server_ip = 1;</code>
       *
       * <pre>
       *server to connect to
       * </pre>
       */
      public boolean hasHttpServerIp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string http_server_ip = 1;</code>
       *
       * <pre>
       *server to connect to
       * </pre>
       */
      public java.lang.String getHttpServerIp() {
        java.lang.Object ref = httpServerIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            httpServerIp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string http_server_ip = 1;</code>
       *
       * <pre>
       *server to connect to
       * </pre>
       */
      public com.google.protobuf.ByteString
          getHttpServerIpBytes() {
        java.lang.Object ref = httpServerIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          httpServerIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string http_server_ip = 1;</code>
       *
       * <pre>
       *server to connect to
       * </pre>
       */
      public Builder setHttpServerIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        httpServerIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string http_server_ip = 1;</code>
       *
       * <pre>
       *server to connect to
       * </pre>
       */
      public Builder clearHttpServerIp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        httpServerIp_ = getDefaultInstance().getHttpServerIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string http_server_ip = 1;</code>
       *
       * <pre>
       *server to connect to
       * </pre>
       */
      public Builder setHttpServerIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        httpServerIp_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object tcIp_ = "";
      /**
       * <code>optional string tc_ip = 2;</code>
       *
       * <pre>
       *traffic controller ip address
       * </pre>
       */
      public boolean hasTcIp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string tc_ip = 2;</code>
       *
       * <pre>
       *traffic controller ip address
       * </pre>
       */
      public java.lang.String getTcIp() {
        java.lang.Object ref = tcIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            tcIp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string tc_ip = 2;</code>
       *
       * <pre>
       *traffic controller ip address
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTcIpBytes() {
        java.lang.Object ref = tcIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tcIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string tc_ip = 2;</code>
       *
       * <pre>
       *traffic controller ip address
       * </pre>
       */
      public Builder setTcIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        tcIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string tc_ip = 2;</code>
       *
       * <pre>
       *traffic controller ip address
       * </pre>
       */
      public Builder clearTcIp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        tcIp_ = getDefaultInstance().getTcIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string tc_ip = 2;</code>
       *
       * <pre>
       *traffic controller ip address
       * </pre>
       */
      public Builder setTcIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        tcIp_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object tcIf_ = "";
      /**
       * <code>optional string tc_if = 3;</code>
       *
       * <pre>
       *interface name to configure traffic controller on
       * </pre>
       */
      public boolean hasTcIf() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string tc_if = 3;</code>
       *
       * <pre>
       *interface name to configure traffic controller on
       * </pre>
       */
      public java.lang.String getTcIf() {
        java.lang.Object ref = tcIf_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            tcIf_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string tc_if = 3;</code>
       *
       * <pre>
       *interface name to configure traffic controller on
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTcIfBytes() {
        java.lang.Object ref = tcIf_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tcIf_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string tc_if = 3;</code>
       *
       * <pre>
       *interface name to configure traffic controller on
       * </pre>
       */
      public Builder setTcIf(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        tcIf_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string tc_if = 3;</code>
       *
       * <pre>
       *interface name to configure traffic controller on
       * </pre>
       */
      public Builder clearTcIf() {
        bitField0_ = (bitField0_ & ~0x00000004);
        tcIf_ = getDefaultInstance().getTcIf();
        onChanged();
        return this;
      }
      /**
       * <code>optional string tc_if = 3;</code>
       *
       * <pre>
       *interface name to configure traffic controller on
       * </pre>
       */
      public Builder setTcIfBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        tcIf_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object binaryShareIp_ = "";
      /**
       * <code>optional string binary_share_ip = 4;</code>
       */
      public boolean hasBinaryShareIp() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string binary_share_ip = 4;</code>
       */
      public java.lang.String getBinaryShareIp() {
        java.lang.Object ref = binaryShareIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            binaryShareIp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string binary_share_ip = 4;</code>
       */
      public com.google.protobuf.ByteString
          getBinaryShareIpBytes() {
        java.lang.Object ref = binaryShareIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          binaryShareIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string binary_share_ip = 4;</code>
       */
      public Builder setBinaryShareIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        binaryShareIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string binary_share_ip = 4;</code>
       */
      public Builder clearBinaryShareIp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        binaryShareIp_ = getDefaultInstance().getBinaryShareIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string binary_share_ip = 4;</code>
       */
      public Builder setBinaryShareIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        binaryShareIp_ = value;
        onChanged();
        return this;
      }

      private rpcdata.ConfigProtos.ConfigReply.PlayerType playerType_ = rpcdata.ConfigProtos.ConfigReply.PlayerType.BCM97208;
      /**
       * <code>optional .protobuftest.ConfigReply.PlayerType player_type = 5 [default = BCM97208];</code>
       */
      public boolean hasPlayerType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .protobuftest.ConfigReply.PlayerType player_type = 5 [default = BCM97208];</code>
       */
      public rpcdata.ConfigProtos.ConfigReply.PlayerType getPlayerType() {
        return playerType_;
      }
      /**
       * <code>optional .protobuftest.ConfigReply.PlayerType player_type = 5 [default = BCM97208];</code>
       */
      public Builder setPlayerType(rpcdata.ConfigProtos.ConfigReply.PlayerType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        playerType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .protobuftest.ConfigReply.PlayerType player_type = 5 [default = BCM97208];</code>
       */
      public Builder clearPlayerType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        playerType_ = rpcdata.ConfigProtos.ConfigReply.PlayerType.BCM97208;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuftest.ConfigReply)
    }

    static {
      defaultInstance = new ConfigReply(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuftest.ConfigReply)
  }

  public interface ConfigRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuftest.ConfigRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>optional string version = 1;</code>
     */
    java.lang.String getVersion();
    /**
     * <code>optional string version = 1;</code>
     */
    com.google.protobuf.ByteString
        getVersionBytes();
  }
  /**
   * Protobuf type {@code protobuftest.ConfigRequest}
   */
  public static final class ConfigRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuftest.ConfigRequest)
      ConfigRequestOrBuilder {
    // Use ConfigRequest.newBuilder() to construct.
    private ConfigRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ConfigRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ConfigRequest defaultInstance;
    public static ConfigRequest getDefaultInstance() {
      return defaultInstance;
    }

    public ConfigRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ConfigRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              version_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rpcdata.ConfigProtos.internal_static_protobuftest_ConfigRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rpcdata.ConfigProtos.internal_static_protobuftest_ConfigRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rpcdata.ConfigProtos.ConfigRequest.class, rpcdata.ConfigProtos.ConfigRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<ConfigRequest> PARSER =
        new com.google.protobuf.AbstractParser<ConfigRequest>() {
      public ConfigRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConfigRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ConfigRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private java.lang.Object version_;
    /**
     * <code>optional string version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string version = 1;</code>
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          version_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string version = 1;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      version_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getVersionBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getVersionBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static rpcdata.ConfigProtos.ConfigRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rpcdata.ConfigProtos.ConfigRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rpcdata.ConfigProtos.ConfigRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rpcdata.ConfigProtos.ConfigRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rpcdata.ConfigProtos.ConfigRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static rpcdata.ConfigProtos.ConfigRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static rpcdata.ConfigProtos.ConfigRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static rpcdata.ConfigProtos.ConfigRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static rpcdata.ConfigProtos.ConfigRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static rpcdata.ConfigProtos.ConfigRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rpcdata.ConfigProtos.ConfigRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuftest.ConfigRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuftest.ConfigRequest)
        rpcdata.ConfigProtos.ConfigRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rpcdata.ConfigProtos.internal_static_protobuftest_ConfigRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rpcdata.ConfigProtos.internal_static_protobuftest_ConfigRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                rpcdata.ConfigProtos.ConfigRequest.class, rpcdata.ConfigProtos.ConfigRequest.Builder.class);
      }

      // Construct using rpcdata.ConfigProtos.ConfigRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rpcdata.ConfigProtos.internal_static_protobuftest_ConfigRequest_descriptor;
      }

      public rpcdata.ConfigProtos.ConfigRequest getDefaultInstanceForType() {
        return rpcdata.ConfigProtos.ConfigRequest.getDefaultInstance();
      }

      public rpcdata.ConfigProtos.ConfigRequest build() {
        rpcdata.ConfigProtos.ConfigRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public rpcdata.ConfigProtos.ConfigRequest buildPartial() {
        rpcdata.ConfigProtos.ConfigRequest result = new rpcdata.ConfigProtos.ConfigRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rpcdata.ConfigProtos.ConfigRequest) {
          return mergeFrom((rpcdata.ConfigProtos.ConfigRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(rpcdata.ConfigProtos.ConfigRequest other) {
        if (other == rpcdata.ConfigProtos.ConfigRequest.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          bitField0_ |= 0x00000001;
          version_ = other.version_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        rpcdata.ConfigProtos.ConfigRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (rpcdata.ConfigProtos.ConfigRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object version_ = "";
      /**
       * <code>optional string version = 1;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string version = 1;</code>
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            version_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string version = 1;</code>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string version = 1;</code>
       */
      public Builder setVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string version = 1;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <code>optional string version = 1;</code>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuftest.ConfigRequest)
    }

    static {
      defaultInstance = new ConfigRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuftest.ConfigRequest)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuftest_ConfigReply_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuftest_ConfigReply_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuftest_ConfigRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuftest_ConfigRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016testData.proto\022\014protobuftest\"\327\001\n\013Confi" +
      "gReply\022\026\n\016http_server_ip\030\001 \001(\t\022\r\n\005tc_ip\030" +
      "\002 \001(\t\022\r\n\005tc_if\030\003 \001(\t\022\027\n\017binary_share_ip\030" +
      "\004 \001(\t\022C\n\013player_type\030\005 \001(\0162$.protobuftes" +
      "t.ConfigReply.PlayerType:\010BCM97208\"4\n\nPl" +
      "ayerType\022\014\n\010BCM97208\020\000\022\013\n\007LINUX32\020\001\022\013\n\007A" +
      "NDROID\020\002\" \n\rConfigRequest\022\017\n\007version\030\001 \001" +
      "(\tB\027\n\007rpcdataB\014ConfigProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuftest_ConfigReply_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuftest_ConfigReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuftest_ConfigReply_descriptor,
        new java.lang.String[] { "HttpServerIp", "TcIp", "TcIf", "BinaryShareIp", "PlayerType", });
    internal_static_protobuftest_ConfigRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuftest_ConfigRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuftest_ConfigRequest_descriptor,
        new java.lang.String[] { "Version", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
